# Built with Jekyll 3.2.0

# Setup
title:               Alessandro Vermeulen
tagline:             'Functional Programming Evangelist'
description:         "Alessandro Vermeulen's blog about languages, programming, Computer Science, photography and the Web."
url:                 'http://alessandrovermeulen.me'
baseurl:             ''

# About/contact
author:
  name:              Alessandro Vermeulen
  url:               https://twitter.com/alevermeulen
  email:             alessandro@alessandrovermeulen.me

# Permalinks

permalink: pretty
# permalink: /:title/

category_dir: blog/categories
tag_dir: tags
paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles


# Set encoding to UTF-8
encoding: utf-8


# Markdown specs
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]

gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5
paginate_path: '/blog/page/:num/'
timezone: Europe/Amsterdam

# Disqus Comments
disqus_short_name: alessandrovermeulen
disqus_show_comment_count: true

# Collections for texts
collections:
  texts:
    output: true
  my_categories:
    output: true
    permalink: /category/:name/
  my_tags:
    output: true
    permalink: /tags/:name/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
